import type { AuditAction, AuditLog } from '../types';

export const AUDIT_ACTIONS: Record<string, AuditAction> = {
    SCHEDULE_GENERATED: 'SCHEDULE' as AuditAction,
    SESSION_RESCHEDULED: 'UPDATE' as AuditAction,
    SESSION_STATUS_UPDATE: 'UPDATE' as AuditAction,
    STAFF_UPDATE: 'UPDATE' as AuditAction,
    MANUAL_OVERRIDE: 'UPDATE' as AuditAction,
    SYSTEM_ALERT: 'VIEW' as AuditAction
};

// Mock Audit Log Store
let auditStore: any[] = Array.from({ length: 45 }).map((_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - (i % 30));
    date.setHours(Math.floor(Math.random() * 8) + 9, Math.floor(Math.random() * 60), 0, 0);

    const actions = Object.keys(AUDIT_ACTIONS);
    const actionKey = actions[Math.floor(Math.random() * actions.length)];
    const users = ['System', 'Dr. Arya', 'Dr. Rahul', 'Admin', 'Automated Scheduler'];

    let details = 'Action performed routinely.';
    let type = 'INFO';
    if (actionKey === 'SYSTEM_ALERT') {
        type = 'WARN';
        details = 'Resource threshold warning detected.';
    } else if (actionKey === 'MANUAL_OVERRIDE') {
        type = 'WARN';
        details = 'User bypassed strict validation rules.';
    } else if (actionKey === 'SCHEDULE_GENERATED') {
        details = 'Automated schedule optimization completed.';
    }

    return {
        id: `log_${i + 1}`,
        timestamp: date.toISOString(),
        action: actionKey,
        user: users[Math.floor(Math.random() * users.length)],
        details,
        type,
        metadata: { info: 'Generated by robust mock system' }
    };
});

const getLogs = async (): Promise<any[]> => {
    return new Promise((resolve) => {
        setTimeout(() => resolve([...auditStore].sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())), 400);
    });
};

const createLog = async (entry: Partial<AuditLog>): Promise<any> => {
    return new Promise((resolve) => {
        setTimeout(() => {
            const newLog = {
                id: `log_${Date.now()}`,
                timestamp: new Date().toISOString(),
                ...entry
            };
            auditStore = [newLog, ...auditStore];
            resolve(newLog);
        }, 200);
    });
};

const auditService = {
    getLogs,
    createLog,
    AUDIT_ACTIONS
};

export default auditService;
