export const AUDIT_ACTIONS = {
    SCHEDULE_GENERATED: 'SCHEDULE_GENERATED',
    SESSION_RESCHEDULED: 'SESSION_RESCHEDULED',
    SESSION_STATUS_UPDATE: 'SESSION_STATUS_UPDATE',
    STAFF_UPDATE: 'STAFF_UPDATE',
    MANUAL_OVERRIDE: 'MANUAL_OVERRIDE',
    SYSTEM_ALERT: 'SYSTEM_ALERT'
};

// Mock Audit Log Store
let auditStore = Array.from({ length: 45 }).map((_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - (i % 30));
    date.setHours(Math.floor(Math.random() * 8) + 9, Math.floor(Math.random() * 60), 0, 0);

    const actions = Object.values(AUDIT_ACTIONS);
    const action = actions[Math.floor(Math.random() * actions.length)];
    const users = ['System', 'Dr. Arya', 'Dr. Rahul', 'Admin', 'Automated Scheduler'];

    let details = 'Action performed routinely.';
    let type = 'INFO';
    if (action === 'SYSTEM_ALERT') {
        type = 'WARN';
        details = 'Resource threshold warning detected.';
    } else if (action === 'MANUAL_OVERRIDE') {
        type = 'WARN';
        details = 'User bypassed strict validation rules.';
    } else if (action === 'SCHEDULE_GENERATED') {
        details = 'Automated schedule optimization completed.';
    }

    return {
        id: `log_${i + 1}`,
        timestamp: date.toISOString(),
        action,
        user: users[Math.floor(Math.random() * users.length)],
        details,
        type,
        metadata: { info: 'Generated by robust mock system' }
    };
});

const getLogs = async () => {
    return new Promise((resolve) => {
        setTimeout(() => resolve([...auditStore].sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp))), 400);
    });
};

const createLog = async (entry) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            const newLog = {
                id: `log_${Date.now()}`,
                timestamp: new Date().toISOString(),
                ...entry
            };
            auditStore = [newLog, ...auditStore];
            resolve(newLog);
        }, 200);
    });
};

const auditService = {
    getLogs,
    createLog,
    AUDIT_ACTIONS
};

export default auditService;
